CREATE TABLE firms
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT    NOT NULL,
    balance_cents INTEGER NOT NULL DEFAULT 0,
    uuid          TEXT    NOT NULL DEFAULT gen_random_uuid()::text,

    CONSTRAINT firms_balance_cents_non_negative CHECK (balance_cents >= 0),
    CONSTRAINT firms_uuid_unique UNIQUE (uuid),
    CONSTRAINT firms_uuid_format
        CHECK (uuid ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);
